persistence:
  enabled: true
  storageClass: "ebs-sc"
  size: 5Gi

controller:
  serviceType: ClusterIP
  admin:
    username: admin
    password: admin
    
  ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hostName: jenkins.zapto.org
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 8080
      tls:
        - hosts:
           - jenkins.zapto.org
          secretName: jenkins-tls
        
  installPlugins:
    - git
    - github
    - github-api
    - github-branch-source
    - docker-workflow
    - kubernetes
    - configuration-as-code
    - workflow-aggregator
    - credentials-binding
    - plain-credentials
    - ssh-credentials
    - matrix-auth
    - pipeline-stage-view
    - pipeline-github-lib
    - antisamy-markup-formatter
    - mailer
    - ws-cleanup
    - workflow-job
    - workflow-cps
    - workflow-basic-steps
    - workflow-durable-task-step
    - dark-theme
    - generic-webhook-trigger
